### PR TITLE
added php 8.0 and 8.1 (as experimental)

### PR DESCRIPTION
**Pull request by oleg-andreyev**

### CODE REVIEW

**Review by OndraM — CHANGES_REQUESTED** [review]
The build is not executing unit tests, can you please have a look?

`Error when evaluating 'continue-on-error' for job 'unit-tests'. (Line: 53, Col: 24): Unexpected value ''`

**Comment by oleg-andreyev** [comment]
@OndraM fixed `continue-on-error`

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Hi @oleg-andreyev 
Thank you for your contribution !
I would welcome this contribution to the QA_5_1 branch of phpMyAdmin :)

**Comment by oleg-andreyev** [comment]
@OndraM please take a look

**Review by OndraM — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
