### PR TITLE
Upload files when W3cCompliant

### PR DESCRIPTION
**Pull request by krazzer**
In RemoteWebElement::sendKeys, a file is not uploaded when isW3cCompliant is true, resulting in attaching a file to a file field always giving the error "file not found", because the local file path is passed, instead of the uploaded file path.

### CODE REVIEW

**Comment by OndraM** [comment]
Unfortunately, W3C WebDriver protocol does not yet include feature to remote file upload: https://github.com/w3c/webdriver/issues/1355

So it for example break Geckodriver build, as the feature is not present here. However it will work in Chrome, as this non-W3C endpoint is implemented here.

If we want to implement some workaround to make it work at least in Chrome, it needs to be done in a bit more complex way (now you would not be able upload even local file in Firefox) - let me check the options.

**Comment by OndraM** [comment]
Replaced by #751

**Comment by OndraM** [comment]
Merged, thanks @krazzer!

**Comment by kirilkirkov** [comment]
@krazzer @OndraM 

When using my selenium code with Docker for file uploads, I encounter an error stating “invalid argument: File not found” for some files, especially those larger than 100MB. 

The exact error message:
**invalid argument: File not found : /Users/user/Downloads/11r/asd.flac
(Session info: chrome=120.0.6099.71)**

This issue doesn’t occur consistently, and I suspect it’s related to file size. Any advice on resolving this problem?

        
`sudo docker run -d -p 4444:4444 -p 5900:5900 --shm-size=2g --restart=always selenium/standalone-chrome:latest`
                
 ```
$fileInput = $this->driver->findElement(WebDriverBy::id("up-field"));
$fileInput->setFileDetector(new LocalFileDetector());
$fileInput->sendKeys('....');
```

**Pull request closed without merging**
