### PR TITLE
Firefox xpi extensions support

### PR DESCRIPTION
**Pull request by maxvgi**
I tried to use php-webdriver with current version of Firefox (61.0) and Selenium (3.13) and found two problems:
* methods findElement and findElements fail
* the extension installation is broken due to changed extension format.

This pull request fixes these problems

### CODE REVIEW

**Comment by OndraM** [comment]
@maxvgi  Also there is #476 - do you think that PR should be closed in favor of this one?

**Comment by maxvgi** [comment]
Hi, @OndraM . Thank you for your reply.

> Also there is #476 - do you think that PR should be closed in favor of this one?

Yes, sure. Firefox does not support extensions with install.rdf manifest since version 53 (April 2017)


> so could you please remove these changes from the PR, so that they won't conflict once the W3C support is merged?

What is the best way to do that? Shall I open a new PR without that commit, containing extensions support changes only?

Concerning to tests, I'll try to make some tests a little bit later.

**Comment by OndraM** [comment]
@maxvgi I think you can remove the lines and force push the commit. Or add new commit removing the change - I will squash it in the end to one commit.

About the tests - so I will wait for you to add them into this PR as well, does it makes sense for you :)?

**Comment by OndraM** [comment]
@maxvgi Hi there - #560 was finally merged and supports Geckodriver. Are you interested to finishing the PR in order to get the extension installation working again for new Firefoxes? Would be great!

If so, please rebase this branch with `community` branch to get Geckodriver builds working :).

**Review by OndraM — CHANGES_REQUESTED** [review]
Needs rebasing on current `main` branch to make sure it works as expected.

**Comment by johndegey** [comment]
Hello,
Any chance that this PR will be merged some day ?
Not being able to load a webextension in Firefox is a big restriction...

Best
John

**Comment by williamdes** [comment]
cc @maxvgi

**Comment by maxvgi** [comment]
Unfortunately I do not use webdriver in my work for now, that's why I cannot complete this PR in the nearest future. But I keep hope to return to this PR in several months.

But I cannot give any promise.

**Comment by alexander-schranz** [comment]
I rebased your PR: #961

**Comment by OndraM** [comment]
Replaced by #961 . Thanks @maxvgi!

**Pull request closed without merging**
