### PR TITLE
Serialize ChromeOptions object under ChromeOptions::CAPABILITY_W3C capability index

### PR DESCRIPTION
**Pull request by gvlasov**
For bug report #849

### CODE REVIEW

**Comment by gvlasov** [comment]
These changes should have been present in https://github.com/php-webdriver/php-webdriver/pull/673

**Review by williamdes — APPROVED** [review]

**Comment by andrewnicols** [comment]
I don't think that this is the right approach. The current approach there is a stop-gap solution which has side-effects as noted in the TODO.

See my alternative proposal in #852

**Comment by andrewnicols** [comment]
I think that we can close this issue now that #852 has landed. Landing this change is not mutually exclusive, but will lead to further b/c breakages in future when we do release 2.0 and stop converting modifying the content of `$this->capabilities`.

Do you agree @OndraM?

**Comment by OndraM** [comment]
Sure, closing this, as it has been covered by #852. Thanks @gvlasov for the suggestion, though!

**Pull request closed without merging**
