### PR TITLE
Fix RemoteWebDriver cannot be instantiated without second parameter

### PR DESCRIPTION
**Pull request by OndraM**
See #789

### CODE REVIEW

**Comment by OndraM** [comment]
It seems this won't be as easy :upside_down_face: .

For example, when using Selenium standalone server, it is IMHO expected to fail - as it obviously doesn't know which browser to start.
```
Facebook\WebDriver\Exception\SessionNotCreatedException: Unable to create session from {
  "desiredCapabilities": {
  },
  "capabilities": {
    "firstMatch": [
      {}
    ]
  }
}
```

**Comment by andrewnicols** [comment]
Maybe we just make it a required param from now on?
API change, so 1.9 target?

**Comment by OndraM** [comment]
> Maybe we just make it a required param from now on?
> API change, so 1.9 target?

API change would mean BC break... However, I think we should keep this allowed - eg. when you run your tests against local Chromedriver, you don't need to specify browser. So I think is it valid to send capabilities empty.

I updated the tests: they are skipped when using Selenium server (or Saucelabs). However they pass when run against specific browser driver.

**Comment by williamdes** [comment]
> So I think is it valid to send capabilities empty.

Is it possible to define default capabilities on a selenium hub, and so sending empty ones would void the config ?

**Comment by OndraM** [comment]
> > So I think is it valid to send capabilities empty.
> 
> Is it possible to define default capabilities on a selenium hub, and so sending empty ones would void the config ?

I don't think so... 🤔 IMHO you must always tell Selenium Hub which in browser you want to create the session.

**Pull request merged**
