### PR TITLE
Add support for sending Chrome DevTools commands

### PR DESCRIPTION
**Pull request by aboks**
ChromeDriver has two endpoints for calling the DevTools API. This PR adds support for calling these endpoints (sending DevTools commands) using php-webdriver.

### CODE REVIEW

**Comment by aboks** [comment]
@OndraM is there anything I could do to help move this PR forward?

**Review by williamdes — APPROVED** [review]

**Comment by OndraM** [comment]
After a further consideration, I think this may need a different approach. Lets wait with finishing it after 1.9.0.

However executing ChromeDevTools protocol is possible since php-webdriver 1.8.0 via [custom commands](https://github.com/php-webdriver/php-webdriver/wiki/Custom-commands):

Send command:
```php
$driver->executeCustomCommand(
    '/session/:sessionId/chromium/send_command', 
    'POST',
    ['cmd' => 'Performance.enable']
);
```
Send command and receive result:
```php
$metrics = $driver->executeCustomCommand(
    '/session/:sessionId/chromium/send_command_and_get_result',
    'POST',
    ['cmd' => 'Performance.getMetrics']
);
```
Send command with parameters and receive result:
```php
$return = $driver->executeCustomCommand(
    '/session/:sessionId/chromium/send_command_and_get_result',
    'POST',
    ['cmd' => 'Runtime.evaluate', 'params' => ['expression' => 'window.location.toString()']]
);
```

**Comment by OndraM** [comment]
Also the endpoint URL was meanwhile changed in chromium to `/session/:sessionId/goog/cdp/execute`

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2307

**Comment by OndraM** [comment]
Replaced by #832 . Thanks @aboks for this initial implementation!

**Comment by OndraM** [comment]
:heavy_check_mark: This feature is now merged and [documented in our wiki](https://github.com/php-webdriver/php-webdriver/wiki/Chrome#chrome-devtools-protocol-cdp) with examples.

**Pull request closed without merging**
