### PR TITLE
Rename repository to php-webdriver/php-webdriver

### PR DESCRIPTION
**Pull request by OndraM**
Repository was transferred, so this is just the first quick change (see #730)

### CODE REVIEW

**Comment by williamdes** [comment]
@OndraM `CODE_OF_CONDUCT`

**Comment by OndraM** [comment]
> @OndraM `CODE_OF_CONDUCT`

Yup, good point. But we may have separate discussion about it and to sort out which COC we will adopt... Do you have ideas regarding this? Or maybe even raise an issue so that we can start the discussion 👌.

**Comment by williamdes** [comment]
https://github.com/php-webdriver/php-webdriver/wiki/ChromeOptions
https://github.com/php-webdriver/php-webdriver/wiki/FirefoxProfile

I fixed an issue URL on another page

**Comment by williamdes** [comment]
>  But we may have separate discussion about it and to sort out which COC we will adopt.

You can remove the FB part and fix it later ?

**Comment by OndraM** [comment]
> https://github.com/php-webdriver/php-webdriver/wiki/ChromeOptions
> https://github.com/php-webdriver/php-webdriver/wiki/FirefoxProfile

Are you able to edit the wiki? I've not yet reviewed all the repository setting (will do later this week), but if so, please feel free to rename it and fix it there :)

**Comment by williamdes** [comment]
I can edit the wiki but need the composer repo name

**Comment by OndraM** [comment]
So `php-webdriver/webdriver` then? I plan to submit the new package to Packagist either later this week or on the begging of the next one.

BTW I think we can continue to refer the project "php-webdriver" like we did so far, ie. the sentences on these pages could simple be:

>  Here is the guide of using ChromeOptions in php-webdriver.

**Comment by williamdes** [comment]
Sounds good, maybe you post a poll on Twitter? 
If you want to make it simple then use your suggestion :)

**Comment by andrewnicols** [comment]
> Sounds good, maybe you post a poll on Twitter?
Wait... people still use Twitter!? ;)

Do we want to continue to have a CLA going forward anyway?

**Comment by williamdes** [comment]
Haha, last time I used Twitter it was for the phpstan poll 😂

Having DCO bot for example could be an idea ?

**Comment by andrewnicols** [comment]
> Having DCO bot for example could be an idea ?

Or even just CLA bot: https://colineberhardt.github.io/cla-bot/#installing-cla-bot

**Pull request merged**
