### PR TITLE
Update HttpCommandExecutor.php

### PR DESCRIPTION
**Pull request by sanduluca**
unescape slashes when encode params

### CODE REVIEW

**Comment by sanduluca** [comment]
Don't quite understand why is it not passing 🤔

**Comment by OndraM** [comment]
Hi, thanks for the contribution! 

Could you please provide some use case why and in what scenario is this change necessary?

(The CI error is probably unrelated, I will have a look.)

**Comment by sanduluca** [comment]
A very common message is one like this
`Curl error thrown for http POST to /session/2104fc08a98b495b6d9d22be647fc3a0/url with params: {"url":"http:\/\/www.example.com\/very\/very\/very\/long\/url"}`
where every slash from URL is escaped and sometimes is hard to understand the link.
I don't  really know why someone will want escaped slashes.
I see this as extra characters, especially when somebody is logging it.

**Review by williamdes — APPROVED** [review]

**Comment by sanduluca** [comment]
Here is comment why JSON_UNESCAPED_SLASHES should be treated as default, but not as option
https://stackoverflow.com/a/45681613

**Comment by OndraM** [comment]
@andrewnicols You think this should go to 2.0? I'd say it should be ok for 1.x.

**Review by OndraM — APPROVED** [review]

**Comment by OndraM** [comment]
Ping @andrewnicols - do you see any BC break?

**Comment by OndraM** [comment]
Hopefully there is not :slightly_smiling_face: .

**Comment by OndraM** [comment]
Thanks @sanduluca!

**Pull request merged**
